/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        paimon: {
          bg: "#f7f3ea",
          surface: "#fffaf0",
          muted: "#f1eadc",
          raised: "#ffffff",
          border: "#ded4bf",
          strong: "#cfc1a6",
          text: "#211b12",
          soft: "#5f5548",
          subtle: "#7d715f",
          accent: "#9a7417",
          accentSoft: "#efe2bd",
          danger: "#bd3c3c",
          success: "#3f7e36",
          successSoft: "#dfedd6",
          info: "#2e6f9e",
          infoSoft: "#dbeaf3",
          dark: {
            bg: "#0f0f0f",
            surface: "#1a1a1a",
            muted: "#141414",
            raised: "#111111",
            border: "#2a2a2a",
            strong: "#333333",
            text: "#ffffff",
            soft: "#aaaaaa",
            subtle: "#888888",
            accent: "#c9a227",
            accentSoft: "#2d2410",
            danger: "#ff6b6b",
            success: "#9de06b",
            successSoft: "#182216",
            info: "#8ec8ff",
            infoSoft: "#202a34",
          },
        },
      },
    },
  },
  plugins: [],
};
